[project]
name = "llm-workflow-patterns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "rizwanc018", email = "rizwanc018@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.4.0",
    "openai>=3.24.0",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "requests>=2.34.2",
]

[project.scripts]
llm-workflow-patterns = "llm_workflow_patterns:main"
prompt-chaining = "llm_workflow_patterns.prompt_chaining.prompt_chaining:main"
routing = "llm_workflow_patterns.routing.routing:main"
parallelization = "llm_workflow_patterns.parallelizaion.parallelization:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
